---
title: John Krebian' Blog
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    category_name: ''
- scope:
    path: ''
    type: posts
  values:
    categories: ''
description: A simple and elegant theme for Jekyll and GitHub Pages.
social_link: twitter
social_username: jkrebian
github_repo: athena
github_username: jkrebian
theme_color: light
remote_theme: jkrebian/athena
baseurl: "/athena"
remote_theme_layouts: 
social_links:
- twitter
- mastodon
- medium
- substack
- hashnode
theme_colors:
- light
- black
- blue
- gray
- magenta
- orange
- red
- white
- yellow
